language: node_js
node_js:
  - "10"
  - "12"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6

sudo: required

os:
  - linux
  - osx

osx_image: xcode7.2

before_install:
  - export TSD_GITHUB_TOKEN=8591f447276e1caa1b9636b9c8053d768130464f
  - node --version
  - npm --version

script:
  - npm run coverage

after_success:
  - npm run coveralls

cache:
  directories:
    - $HOME/.npm
    - node_modules
