export const AlgorithmNames = {
    RsaSSA: "RSASSA-PKCS1-v1_5",
    RsaPSS: "RSA-PSS",
    RsaOAEP: "RSA-OAEP",
    AesECB: "AES-ECB",
    AesCTR: "AES-CTR",
    AesCMAC: "AES-CMAC",
    AesGCM: "AES-GCM",
    AesCBC: "AES-CBC",
    AesKW: "AES-KW",
    Sha1: "SHA-1",
    Sha256: "SHA-256",
    Sha384: "SHA-384",
    Sha512: "SHA-512",
    ChaCha20: "CHACHA20",
    EcDSA: "ECDSA",
    EdDSA: "EDDSA",
    EcDH: "ECDH",
    Hmac: "HMAC",
    Poly1305: "POLY1305",
    Pbkdf2: "PBKDF2",
    X25519: "X25519",
};
